### ISSUE TITLE
Chat is constantly disconnecting

### ISSUE THREAD

**Issue by ghost** [OwenGHB/angband-webclient#12]
Every few minutes I get a message like this:
***Disconnected***

**Comment by OwenGHB** [comment]
This happens to me a lot too - which is why I added the warning that there was a disconnect. I'm not certain why it's happening (the server should be pinging the chatsockets every 10 seconds to prevent it). The next thing I was going to do here was make an automatic attempt to reconnect, after telling the user they are disconnected.

**Comment by ghost** [comment]
Needs investigation. I might try to pick this one off after I've ramped up on the rest of the project.
