### ISSUE TITLE
Oangband: Rogue-like keys and ESC key don't work normally

### ISSUE THREAD

**Issue by smbhax** [OwenGHB/angband-webclient#53]
- Start a game of Oangband 1.1.0u on angband.live
- Get to a town or dungeon area
- Press = for Options
- Press i for Interface Options
- Press a to set Rogue-like commands to "yes"
- Press ESC to back out
==> Nothing happens. Pressing ESC twice may back out, with a small delay. Curiously, pressing ' (aka the tilde key, right below ESC on the keyboard) does back out immediately with a single press.
- Get back to the town/dungeon view
- Try moving with the Rogue-like keys (HJKLYUBN)
==> The character does not move; the game is still interpreting those keys as standard keyset command keys, rather than roguelike keyset movement commands

I'm not sure if this is a bug with the unix/linux version of Oangband, or with the angband.live web interface--but it doesn't happen in the unofficial Windows client (http://angband.oook.cz/faangband/Fonts.html). I've seen the ESC key thing mentioned as a general curses (over SSH?) issue: http://angband.oook.cz/forum/showpost.php?p=26173&postcount=2 -- but it doesn't happen in the other games I've tried on angband.live.

**Comment by OwenGHB** [comment]
This is a peculiarity of many older versions and variants, the escape key itself is intended to still be able to be used to input escape sequences. You can use ` as a substitute for escape when playing these variants. While it would be possible to backport the change which has escape working normally to all these older versions and variants, given the existence of the ` workaround I'm inclined to simply present them 'as is' without code changes. Likewise the non-functioning roguelike keys would be a bug within the variant itself, rather than the web service.

**Comment by smbhax** [comment]
If these are bugs with the latest code of the game itself, I completely agree that leaving them as is is the way to go. I entered this as an issue for angband.live only because they don't exist in the game's most recent available Windows binary, so I wasn't sure if they were in the game code, or had somehow been caused by being run through the service.

**Comment by smbhax** [comment]
If these are bugs with the latest code of the game itself, I completely agree that leaving them as is is the way to go. I entered this as an issue for angband.live only because they don't exist in the game's most recent available Windows binary, so I wasn't sure if they were in the game code, or had somehow been caused by being run through the service. Since you've confirmed they're in the game itself, I'm closing the issue.
